package br.com.zup.edu.keymanager.register

import br.com.zup.edu.keymanager.external.bcb.PixTypeBcb

enum class PixType {
    CPF {
        override fun validation(value: String?): Boolean {
            if (value.isNullOrBlank()) {
                return false
            }

            return value.matches("^[0-9]{11}".toRegex())
        }
    },
    EMAIL {
        override fun validation(value: String?): Boolean {
            if (value.isNullOrBlank()) {
                return false
            }

            return value.matches("^[a-zA-Z0-9.!#\$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*\$".toRegex())
        }
    },
    TELEFONE {
        override fun validation(value: String?): Boolean {
            if (value.isNullOrBlank()) {
                return false
            }

            return value.matches("^\\+[1-9][0-9]\\d{1,14}\$".toRegex())
        }
    },
    CHAVE_ALEATORIA {
        override fun validation(value: String?): Boolean {
            //this key will be autogenerated and your value can be blank
            return value.isNullOrBlank()
        }
    };

    fun converter(): PixTypeBcb {
        return when (this) {
            CPF -> PixTypeBcb.CPF
            EMAIL -> PixTypeBcb.EMAIL
            TELEFONE -> PixTypeBcb.PHONE
            else -> PixTypeBcb.RANDOM
        }
    }

    abstract fun validation(value: String?): Boolean
}