micronaut:
  application:
    name: keyManager

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/db_keymanager
    driverClassName: org.postgresql.Driver
    username: postgres
    password: changeme
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: create-drop
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true


erp:
  itau:
    client:
      host: 'http://localhost:9091'
      endpoint:
          contas: '/api/v1/clientes/{clienteId}/contas'
          client: '/api/v1/clientes/{clienteId}'